//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudInfo_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dnevnik
    {
        public int Id { get; set; }
        public string Theme { get; set; }
        public Nullable<int> Ocenka { get; set; }
        public int Id_Student { get; set; }
    }
}
